/**
 * Capability registry tests.
 *
 * src/capabilities.ts is generated by scripts/generate-capabilities.mjs from capabilities.plan.json.
 * These tests cover the emitted registry (so it is not an untested generated file) and assert the
 * contract the MCP projection and non-TypeScript consumers rely on.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  CAPABILITY_REGISTRY, CAPABILITY_NAMES, CAPABILITIES_PLAN_HASH, getCapability,
} from '../src/capabilities.js';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const records = Object.values(CAPABILITY_REGISTRY);
const planText = readFileSync(join(root, 'capabilities.plan.json'), 'utf8');
const plan = JSON.parse(planText) as {
  operations: Array<{ primitive: string | null; helper: string | null; effect: string; status: string }>;
};

describe('capability registry', () => {
  it('is generated, not hand-edited, and carries the plan hash', () => {
    const src = readFileSync(join(root, 'src', 'capabilities.ts'), 'utf8');
    expect(src).toContain('MACHINE-GENERATED');
    expect(src).toContain('DO NOT HAND-EDIT');
    expect(/^\s*import\s/m.test(src), 'the registry must have zero imports').toBe(false);
    expect(CAPABILITIES_PLAN_HASH).toBe(createHash('sha256').update(planText).digest('hex'));
  });

  it('emits one record per implemented operation, keyed by its name', () => {
    expect(records.length).toBeGreaterThan(0);
    expect(CAPABILITY_NAMES).toEqual(Object.keys(CAPABILITY_REGISTRY));
    for (const r of records) expect(r.name).toBeTruthy();
    const names = records.map((r) => r.name);
    expect(new Set(names).size).toBe(names.length);
    for (const name of CAPABILITY_NAMES) expect(getCapability(name)?.name).toBe(name);
  });

  it('never emits a record for a row that is still planned', () => {
    const emitted = new Set(records.map((r) => r.name));
    for (const row of plan.operations) {
      const name = row.primitive ?? row.helper;
      if (name && (row.status === 'implemented' || row.status === 'tested')) continue;
      if (name) expect(emitted.has(name), `${name} has no record while status=${row.status}`).toBe(false);
    }
  });

  it('carries the full contract on every record', () => {
    for (const r of records) {
      expect(r.purpose, `${r.name} purpose`).toBeTruthy();
      expect(r.inputSchema, `${r.name} inputSchema`).toBeTypeOf('object');
      // A no-parameter endpoint (e.g. api_info.get) legitimately has an empty schema object.
      expect(r.outputSchema, `${r.name} outputSchema`).toBeTruthy();
      expect(r.examples.length, `${r.name} examples`).toBeGreaterThan(0);
      expect(r.permissions, `${r.name} permissions`).toBeTruthy();
      expect(r.errors.length, `${r.name} errors`).toBeGreaterThan(0);
      expect(r.usage, `${r.name} usage`).toBeTruthy();
      expect(r.pagination, `${r.name} pagination`).toBeTruthy();
      expect(r.retry, `${r.name} retry`).toBeTruthy();
      expect(['primitive', 'helper']).toContain(r.kind);
    }
  });

  it('marks every mutation as dry-runnable', () => {
    for (const r of records) {
      if (r.effect === 'read') expect(r.dryRun, `${r.name} is a read`).toBe(false);
      else expect(r.dryRun, `${r.name} is a mutation and must be dry-runnable`).toBe(true);
    }
  });

  it('classifies every destructive operation as approval-worthy', () => {
    for (const r of records) {
      if (r.effect === 'destructive') expect(r.flags).toContain('requiresApproval');
    }
  });

  it('gives every helper a usage caveat and a resolution or compact answer', () => {
    for (const r of records) {
      if (r.kind !== 'helper') continue;
      expect(r.usage, `${r.name} usage`).toBeTruthy();
      expect(r.compact !== undefined).toBe(true);
    }
  });

  it('does not claim pagination and non-pagination at once', () => {
    for (const r of records) {
      const p = r.pagination as { mode?: string; nonPaginated?: boolean };
      if (p.nonPaginated === true) expect(p.mode, `${r.name}`).not.toBe('page');
    }
  });
});
