/**
 * mcp-server.ts — reference Model Context Protocol (MCP) v2 server backed by node-hudu.
 *
 * Protocol 2026-07-28, official SDK v2 (`@modelcontextprotocol/server`), zod v4
 * (`import * as z from 'zod/v4'`), `structuredContent` paired with an `outputSchema` per tool.
 *
 * Ground rules this example follows (see MCP_TOOL_MANIFEST.md, curated by MCP_TOOL_OVERRIDES.json):
 * - Every READ tool calls the SDK's HELPER tier: `search`, `findBy*`, `resolve`, `getContext`, or
 *   the cross-resource `operations.searchAcrossResources` / `operations.resolveAny`. No tool is
 *   backed by `listAll`, `listPages`, or a streaming `list`.
 * - Results are BOUNDED: `limit` defaults to 25 and hard-caps at 100 on every read tool. The SDK
 *   validates the bound and throws `CONFIG_ERROR` above it — it never silently clamps.
 * - Every MUTATING tool exposes `dry_run`, which calls the SDK's `{ dryRun: true }` path and
 *   returns a `DryRunResult` (`simulated: true`, impact, diff) without issuing the write.
 * - Tool names, titles and descriptions are the curated ones from `MCP_TOOL_MANIFEST.md`;
 *   `npm run mcp:project -- --check-example` fails if this file drifts from that manifest.
 * - Errors surface `HuduError.code` (NOT_FOUND, RESOLUTION_AMBIGUOUS, POLICY_DENIED, …) so a
 *   model can self-correct instead of retrying blindly.
 *
 * PROGRESSIVE DISCLOSURE (design doc `progressive-disclosure.md`, kept outside this repo): this
 * is a REFERENCE
 * CONSUMER, and the tool list it registers is the generated CORE profile — the curated manifest
 * projects 139 tools, of which a client must carry all 139 on every turn. The CORE set (rule in
 * `scripts/project-mcp-tools.mjs`, generated into `src/mcp/catalog.generated.ts`) is the
 * small always-present surface: R1 discover (`hudu_catalog` / `hudu_describe` / `hudu_invoke`),
 * R2 identify the tenant, R3 find a record the caller cannot name, R4 one read entry per group-A
 * workflow resource. Every OTHER operation stays REACHABLE through `hudu_invoke`, which validates
 * against the registry record before any request, forces a dry run on writes and refuses a
 * destructive operation without its confirmation flag. Nothing is removed from the surface: the
 * 56 operations curation dropped as duplicate outcomes and the 22 the projection never exposes are
 * catalogued as rows (the refused ones with `reachable: false` and the reason).
 *
 * Declared profile: `core`. `HUDU_MCP_PROFILE=extended|all` is the host knob documented in
 * MCP_TOOL_MANIFEST.md; this reference server demonstrates the `core` profile only.
 *
 * Requires:  npm install @modelcontextprotocol/server zod      (both are devDependencies here)
 * Run with:  HUDU_BASE_URL=https://hudu.example.com HUDU_API_KEY=xxx npx tsx examples/mcp-server.ts
 *
 * Note: MCP SDK v2 requires Node >= 20.
 */
import { McpServer } from '@modelcontextprotocol/server';
import { serveStdio } from '@modelcontextprotocol/server/stdio';
import * as z from 'zod/v4';
import { HuduClient } from 'node-hudu';
import { Operations } from 'node-hudu/operations';
import { getCapability } from 'node-hudu/capabilities';
// `node-hudu/mcp` — generated by `node scripts/build-tool-catalog.mjs` from the capability registry
// into `src/mcp/catalog.generated.ts`, and compiled into the published package like every other
// subpath, so a host that only has the tarball can import it. DO NOT HAND-EDIT the generated file.
// It carries the CORE profile, the three META tool specs, the catalog rows and the runtime DATA
// helpers (catalog paging, catalog lookup, describe). It carries NO validator and NO write
// governor: those live in exactly one place, the SDK's `operations.invoke`, which this server
// calls. It imports nothing at runtime: the SDK stays MCP-independent and this server passes the
// registry record in.
import {
  META_TOOLS,
  SEARCH_HELP,
  SEARCH_MODES,
  SEARCH_RESOURCES,
  TOOL_DESCRIPTIONS,
  catalogPage,
  configError,
  describeOperation,
  requireCatalogRow,
} from 'node-hudu/mcp';

const baseUrl = process.env.HUDU_BASE_URL;
const apiKey = process.env.HUDU_API_KEY;

if (!baseUrl || !apiKey) {
  throw new Error('HUDU_BASE_URL and HUDU_API_KEY must be set');
}

/**
 * The profile this example registers, read by `npm run mcp:project -- --check-example` (which then
 * requires exactly the generated CORE set + the three META tools, with their descriptions verbatim).
 * `core` is the token-budget profile; see the header. The extended profile is the curated manifest
 * (139 tools) and is not demonstrated here on purpose — a reference server that shipped 139 tools
 * would be the problem this design removes.
 */
const MCP_PROFILE = 'core';

/** Helper `limit` bounds (manifest: "default 25 results, hard maximum 100"). */
const DEFAULT_LIMIT = 25;
const MAX_LIMIT = 100;

/** The eight resources the cross-resource helpers can reach, in their documented fan-out order. */
const SEARCHABLE_RESOURCES = z.array(
  z.enum([
    'companies',
    'articles',
    'assets',
    'websites',
    'asset_passwords',
    'password_folders',
    'groups',
    'users',
  ]),
);

/** Every read tool's bound, stated identically everywhere. */
const LIMIT = z
  .number()
  .int()
  .min(1)
  .max(MAX_LIMIT)
  .default(DEFAULT_LIMIT)
  .describe('Maximum rows returned (1-100, default 25). A larger value throws CONFIG_ERROR - the SDK never silently clamps.');

const EXPAND = z
  .boolean()
  .default(false)
  .describe('Return the full typed records instead of the compact summaries (default false).');

const DRY_RUN = z
  .boolean()
  .default(false)
  .describe('Validate without issuing the write: returns a DryRunResult with simulated: true, the impact and the diff. Dry-run every destructive or approval-gated call first.');

/** Accepts a bare id/name/slug or the identifier object the resource documents. */
const IDENTIFIER = z.union([
  z.number().int(),
  z.string().min(1),
  z.object({
    id: z.number().int().optional().describe('Numeric id - the direct fetch.'),
    name: z.string().optional().describe('Exact name.'),
    slug: z.string().optional().describe('Exact slug.'),
    external_id: z.string().optional().describe('Vendor-side external id.'),
    domain: z.string().optional().describe('Domain, for resources that have one.'),
  }),
]);

/** `companies.resolve` also accepts a website. */
const COMPANY_IDENTIFIER = z.union([
  z.number().int(),
  z.string().min(1),
  z.object({
    id: z.number().int().optional(),
    name: z.string().optional(),
    slug: z.string().optional(),
    website: z.string().optional(),
    domain: z.string().optional(),
  }),
]);

/** `assets.resolve` / `assets.getContext` also accept a primary serial and a company scope. */
const ASSET_IDENTIFIER = z.union([
  z.number().int(),
  z.string().min(1),
  z.object({
    id: z.number().int().optional(),
    companyId: z.number().int().optional(),
    name: z.string().optional(),
    slug: z.string().optional(),
    primary_serial: z.string().optional(),
  }),
]);

/**
 * Row shape of a compact summary (`CompanySummary`, `ArticleSummary`, …).
 *
 * Stays loose on purpose: the exact kept/dropped field list is published per resource in
 * MCP_TOOL_MANIFEST.md (`outputSchema.drops`). Restating it here would add ~15 fields of JSON
 * schema per resource for no extra information the model does not already have.
 */
const ROWS = z.array(z.unknown());

/** One row of a bounded list result. `hasMore` is a hint: the SDK returned exactly `limit` rows. */
const LIST_OUTPUT = z.object({
  items: ROWS,
  total: z.number(),
  limit: z.number(),
  hasMore: z.boolean(),
});

/** One resolved record: `found: false` is a complete answer, not an error. */
const ONE_OUTPUT = z.object({ found: z.boolean(), record: z.unknown() });

/** A cross-resource result; `truncated` names resources whose scan hit its cap (undecided). */
const HITS_OUTPUT = z.object({
  hits: z.array(
    z.object({ resource: z.string(), id: z.number(), label: z.string(), item: z.unknown() }),
  ),
  total: z.number(),
  truncated: z.array(z.string()),
  scanned: z.number(),
});

/**
 * `hudu_search` returns ONE shape per mode, each echoing the mode that ran, so a response can never
 * be misread as another mode's (design doc `single-search-tool.md` 1.4 R4, kept outside this repo).
 */
const SEARCH_OUTPUT = z.union([
  z.object({ mode: z.literal('search'), query: z.string(), hits: z.array(z.unknown()), meta: z.unknown() }),
  z.object({ mode: z.literal('help'), topic: z.string(), help: z.unknown() }),
  z.object({ mode: z.literal('resources'), resources: z.unknown(), modes: z.array(z.string()) }),
]);

/** A bundled context read (`getContext`, `getWithTasks`). */
const CONTEXT_OUTPUT = z.object({ context: z.unknown() });

/** A catalog page (`hudu_catalog`): counts plus the rows the filters matched. */
const CATALOG_OUTPUT = z.object({
  total_operations: z.number(),
  reachable_operations: z.number(),
  unexposed_operations: z.number(),
  unreachable_operations: z.number(),
  matched: z.number(),
  offset: z.number(),
  limit: z.number(),
  has_more: z.boolean(),
  rows: z.array(z.unknown()),
});

/** An `hudu_invoke` result: `simulated: true` means the dry-run path ran and nothing was written. */
const INVOKE_OUTPUT = z.object({ simulated: z.boolean(), operation: z.string(), result: z.unknown() });

/** A write result: `simulated: true` means the dry-run path ran and nothing was written. */
const WRITE_OUTPUT = z.object({ simulated: z.boolean(), result: z.unknown() });

type ToolReturn =
  | { content: Array<{ type: 'text'; text: string }>; structuredContent: Record<string, unknown> }
  | { content: Array<{ type: 'text'; text: string }>; isError: true };

/** A successful structured result. `outputSchema` describes `structuredContent`. */
function ok(text: string, structuredContent: Record<string, unknown>): ToolReturn {
  return { content: [{ type: 'text', text }], structuredContent };
}

/** Bounded list result: the count is the number of rows actually returned. */
function listResult(what: string, items: unknown[], limit: number): ToolReturn {
  return ok(`${items.length} ${what} record(s) returned (bound ${limit}).`, {
    items,
    total: items.length,
    limit,
    hasMore: items.length >= limit,
  });
}

/** One-record result. A `null` from a helper is a complete, bounded "no match" answer. */
function oneResult(what: string, record: unknown): ToolReturn {
  return ok(record === null ? `No ${what} matched.` : `${what} resolved.`, {
    found: record !== null,
    record,
  });
}

/** Surface `HuduError.code` (and HTTP status) so the model can correct itself. */
function errorContent(err: unknown): ToolReturn {
  const code = (err as { code?: string })?.code;
  const status = (err as { status?: number })?.status;
  const message = err instanceof Error ? err.message : String(err);
  return {
    content: [{ type: 'text', text: JSON.stringify({ error: true, code, status, message }) }],
    isError: true,
  };
}

const handle = serveStdio(() => {
  const hudu = new HuduClient({ baseUrl, apiKey });
  /** Cross-resource reads (`searchAcrossResources`, `resolveAny`); same client, no extra config. */
  const ops = new Operations(hudu);

  const server = new McpServer({
    name: 'hudu-mcp',
    version: '0.3.0',
    title: 'Hudu MCP Server',
    websiteUrl: 'https://github.com/msoukhomlinov/node-hudu',
  });


  // =========================================================================================
  // META TOOLS (R1) - the generated catalog, the per-operation describe, and the escape hatch.
  // Always present, and the reason the 147-tool curated surface is reachable without being paid
  // for on every turn. `hudu_invoke` is safe through the SDK's own dispatcher, not through this
  // shorter tool list: `operations.invoke` validates the registry record before any request, is
  // dry-run-first on writes, and needs `confirm` to equal the operation key for a destructive one.
  // This server adds NO validator and NO governor of its own — one implementation decides.
  // =========================================================================================
  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_catalog',
    {
      title: 'Discover Operations (Catalog)',
      description: 'List the operations the Hudu SDK implements, with the tool that exposes each one (when it has one), its effect, whether it needs a dry run or a confirmation flag, and the arguments it requires. The tool list on this server is a SUBSET: this is a curated core profile, and the catalog is how you discover a capability that has no tool of its own — find the row, call hudu_describe for the exact schema, then hudu_invoke. Rows with no "tool" are reachable only through hudu_invoke. Rows with "reachable": false are deliberately not callable here and state why (an unbounded read, or a binary/download surface). Bounded: limit defaults to 40 and is hard-capped at 100, offset pages through the rest; the whole catalog is ~10k tokens, so ask for a filter or a page rather than dumping it.',
      inputSchema: z.object({
        limit: z.number().int().min(1).max(100).default(40).describe('Rows per page (1-100, default 40); the whole catalog is ~10k tokens, so page it.'),
        offset: z.number().int().min(0).default(0).describe('Row offset, for paging.'),
        effect: z.enum(['read', 'write', 'destructive']).optional().describe('Only rows with this effect.'),
        resource: z.string().optional().describe('Only rows of this registry resource (e.g. "assets").'),
        unexposed_only: z.boolean().optional().describe('Only rows with NO tool of their own — the capabilities reachable only through hudu_invoke.'),
      }),
      outputSchema: CATALOG_OUTPUT,
      annotations: { readOnlyHint: false, openWorldHint: true },
      _meta: { backingOperation: '— (serves the whole registry)', dryRunAffordance: "dry_run", registryWide: true },
    },
    async (args) => {
      try {
        const page = catalogPage(args);
        const text = `${page.rows.length} of ${page.matched} matching operation(s) shown (offset ${page.offset}, bound ${page.limit}). The registry holds ${page.total_operations} operations; ${page.unexposed_operations} of them have NO tool of their own and are reached with hudu_invoke; ${page.unreachable_operations} are deliberately not callable here (see the row's reason and bounded alternative).`;
        return ok(text, { ...page });
      } catch (err) {
        return errorContent(err);
      }
    },
  );
  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_describe',
    {
      title: 'Describe One Operation',
      description: 'Return the full input schema, effect, flags, dry-run support, error vocabulary, related operations and preferredWhen guidance for ONE operation, so a capability can be called correctly without carrying every schema in context. Use it after hudu_catalog named the operation and before hudu_invoke. Takes the canonical operation key exactly as the catalog prints it (for example "companies.update") — never a tool name, and there is no fuzzy matching: an unknown key is a CONFIG_ERROR naming the nearest catalog keys.',
      inputSchema: z.object({
        operation: z.string().min(1).describe('Canonical operation key exactly as hudu_catalog prints it, e.g. "companies.update". Never a tool name; there is no fuzzy match.'),
      }),
      outputSchema: z.object({ op: z.string() }).passthrough(),
      annotations: { readOnlyHint: false, openWorldHint: true },
      _meta: { backingOperation: '— (serves the whole registry)', dryRunAffordance: "dry_run", registryWide: true },
    },
    async (args) => {
      try {
        const { operation } = args;
        const record = getCapability(operation);
        // Unknown key: requireCatalogRow throws CONFIG_ERROR naming the nearest catalog keys
        // (exact-key lookup only — there is no fuzzy execution anywhere in this server).
        if (record === undefined) requireCatalogRow(operation);
        const described = describeOperation(record);
        return ok(`${operation}: ${described.effect}${described.reachable ? '' : ' — NOT callable here: ' + described.why_not}`, { ...described });
      } catch (err) {
        return errorContent(err);
      }
    },
  );
  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_invoke',
    {
      title: 'Invoke Any Operation (Escape Hatch)',
      description: 'Execute an operation by its canonical registry key, including the ones with no tool of their own. Every call goes through the SDK dispatcher `operations.invoke`: the input is validated against the registry record BEFORE any HTTP request — unknown fields, missing required fields, wrong types and out-of-enum values are refused with CONFIG_ERROR and the field path, and no request is issued. Reads run directly. Writes are dry-run-first: omit dry_run (or pass dry_run: true) and nothing is written — the SDK dry-run path runs and returns simulated: true with the impact and the diff; pass dry_run: false to execute. A destructive or approval-gated operation also requires confirm to equal the operation key exactly, and a confirmed destructive call is still only a dry run unless dry_run: false is also passed. Operations the projection never exposes (unbounded listAll/listPages reads, binary/download resources) are refused with a reason and the bounded alternative where one exists. This is the escape hatch for the long tail, not the common path: prefer a typed tool when one fits, and read the schema with hudu_describe first when the arguments are not obvious.',
      inputSchema: z.object({
        operation: z.string().min(1).describe('Canonical operation key (see hudu_catalog). Exact registry key, never a tool name.'),
        input: z.record(z.string(), z.unknown()).optional().describe('The operation arguments as one object; validated against the registry record before any request.'),
        dry_run: z.boolean().optional().describe('Writes only: omit (or pass true) for the SDK dry-run path (simulated: true, impact and diff, no request issued); pass false to execute. A read called with dry_run: true is refused.'),
        confirm: z.string().optional().describe('For a destructive or approval-gated operation: must equal the operation key exactly, or the call is refused.'),
      }),
      outputSchema: INVOKE_OUTPUT,
      annotations: { readOnlyHint: false, openWorldHint: true },
      _meta: { backingOperation: '— (whole registry, by canonical key)', dryRunAffordance: "dry_run", registryWide: true },
    },
    async (args) => {
      const { operation, input, dry_run, confirm } = args;
      try {
        // ONE implementation decides whether this call is allowed: the SDK dispatcher
        // (`operations.invoke`). It resolves the exact registry key (naming the nearest real keys
        // when the key is unknown), refuses the projection's refusal class, validates the bag
        // against that record's inputSchema, forces a dry run first on writes, requires `confirm`
        // for a destructive one, and then calls the operation's OWN typed method positionally —
        // so this server re-implements neither dispatch nor governance, and inherits the schema
        // language the SDK's G4 test walks over every registry record.
        const opts: { dryRun?: boolean; confirm?: string } = {};
        if (dry_run !== undefined) opts.dryRun = dry_run;
        if (confirm !== undefined) opts.confirm = confirm;
        const result = await hudu.operations.invoke(operation, (input ?? {}) as Record<string, unknown>, opts);
        const simulated = result !== null && typeof result === 'object' && (result as { simulated?: unknown }).simulated === true;
        return ok(
          simulated ? `Dry run: nothing was written (${operation}).` : `${operation} completed.`,
          {
            simulated,
            operation,
            result: result ?? null,
          },
        );
      } catch (err) {
        return errorContent(err);
      }
    },
  );

  // =========================================================================================
  // CORE READ TOOLS (R2 / R3 / R4) - helper tier only (search / resolve / getContext).
  // =========================================================================================

  // ---------------------------------------------------------------------------------------
  // ---------------------------------------------------------------------------------------
  // hudu_search — ONE self-describing search tool with three modes (search | help | resources).
  //
  // Mode discipline by construction, not by hope (design doc `single-search-tool.md` 1.4, kept outside this repo):
  //   - `mode` is optional and defaults to "search": the hot path is unchanged and no field is
  //     conditionally required;
  //   - a missing `query` in search mode is a CONFIG_ERROR that NAMES mode:"help" - it never
  //     silently becomes help, and help is never returned implicitly;
  //   - a field the selected mode cannot honour is a CONFIG_ERROR naming the fields that mode
  //     DOES honour - no field is ever quietly ignored;
  //   - every mode returns a DISTINCT top-level shape with the mode echoed back, so a response
  //     cannot be misread as another mode's.
  //
  // SEARCH MODE DEFAULTS TO tier: "index" - the tool builds or awaits the body index instead of
  // answering body-blind from the vendor tier. The SDK default stays lazy (tier "auto") for
  // programmatic callers; a TOOL must not hand an agent a degraded answer by default. A cold
  // answer is still possible and always says so in `meta.degraded`.
  server.registerTool(
    'hudu_search',
    {
      title: 'Search Hudu (search | help | resources)',
      description: TOOL_DESCRIPTIONS['hudu_search'],
      inputSchema: z.object({
        mode: z
          .enum(['search', 'help', 'resources'])
          .default('search')
          .describe('Which mode to run. Default "search" (the query runs; nothing else is needed). "help" returns how to use this tool. "resources" returns what is searchable. A field the selected mode cannot honour is a CONFIG_ERROR naming the fields it does honour - never silently ignored.'),
        query: z
          .string()
          .min(1)
          .optional()
          .describe('mode="search" only, and REQUIRED there: omitting it is a CONFIG_ERROR naming mode:"help" (it never falls back to help). Typos, partial words and reordered words are tolerated; article BODY content is searched.'),
        resources: z
          .array(z.enum(['articles', 'assets', 'companies', 'users', 'groups', 'websites', 'asset_passwords', 'password_folders']))
          .optional()
          .describe('mode="search" only. Which resources to search; default ["articles","assets"]. Exactly the resources whose list endpoint declares a search vendor filter.'),
        topic: z
          .enum(['core', 'all', 'query', 'limits', 'scoring', 'degradation', 'results', 'followup'])
          .optional()
          .describe('mode="help" only. Which help section to return (default "core"; "all" adds query syntax and scoring). Rejected in the other modes.'),
        limit: z.number().int().min(1).max(25).optional().describe('mode="search" only. Ranked hits: 1-25, default 8. A larger value is a CONFIG_ERROR, never clamped.'),
        snippetChars: z.number().int().min(0).max(400).optional().describe('mode="search" only. Snippet characters per hit: 0-400, default 200, 0 = no snippet.'),
        company_id: z.number().int().optional().describe('mode="search" only. Scope the scan to one company.'),
        updated_since: z.string().optional().describe('mode="search" only. ISO 8601; only records updated at or after it.'),
        min_score: z.number().optional().describe('mode="search" only. 0-100 band floor; dropped hits are counted so a threshold never looks like absence.'),
        exact_only: z.boolean().optional().describe('mode="search" only. true disables fuzzy matching, still ranked and snippeted. Default false.'),
        tier: z
          .enum(['auto', 'vendor', 'index'])
          .optional()
          .describe('mode="search" only. THIS TOOL DEFAULTS TO "index" (build or await the body index, so the answer is complete rather than body-blind). "auto" is the SDK default for programmatic callers; "vendor" answers from Hudu search alone.'),
        refresh: z.boolean().optional().describe('mode="search" only. true forces a body-index rebuild before answering.'),
      }),
      outputSchema: SEARCH_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'operations.searchKnowledge', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      const mode = args.mode ?? 'search';
      const spec = SEARCH_MODES.find((m) => m.mode === mode);
      if (!spec) {
        return errorContent(
          configError(
            `hudu_search: mode must be one of ${SEARCH_MODES.map((m) => m.mode).join(' | ')} (got ${JSON.stringify(args.mode)}). The mode names in the response are exactly these strings.`,
          ),
        );
      }
      // R3: a field the mode cannot honour is a CONFIG_ERROR naming the fields it does honour.
      const provided = Object.keys(args).filter((k) => k !== 'mode' && args[k] !== undefined);
      const unhonoured = provided.filter((k) => spec.rejects.includes(k));
      if (unhonoured.length) {
        return errorContent(
          configError(
            `hudu_search: mode="${mode}" cannot honour ${unhonoured.join(', ')}. It honours: ${spec.fields.join(', ')}. ` +
              (mode === 'search' ? 'mode="help" honours topic if you wanted the help text.' : 'Drop the field, or use the mode that honours it.') +
              ' A field a mode cannot honour is never silently ignored.',
          ),
        );
      }
      if (mode === 'help') {
        const topic = args.topic ?? SEARCH_HELP.default;
        if (!SEARCH_HELP.sections.includes(topic)) {
          return errorContent(
            configError(`hudu_search: topic must be one of ${SEARCH_HELP.sections.join(' | ')} (got ${JSON.stringify(topic)}).`),
          );
        }
        const chosen = topic === 'core' ? SEARCH_HELP.core : topic === 'all' ? SEARCH_HELP.all : [topic];
        const text = chosen.map((s) => SEARCH_HELP.text[s]).join('\n\n');
        return ok(`hudu_search help (${chosen.join(', ')}).`, {
          mode: 'help',
          topic,
          help: {
            text,
            sections: chosen,
            bytes: Buffer.byteLength(text, 'utf8'),
            defaults: { mode: 'search', tier: 'index', limit: 8, snippetChars: 200, resources: ['articles', 'assets'] },
            modes: SEARCH_MODES,
            resourcesDerivedFrom: SEARCH_RESOURCES.derivedFrom,
          },
        });
      }
      if (mode === 'resources') {
        return ok(
          `${SEARCH_RESOURCES.count} searchable resource(s); ${SEARCH_RESOURCES.notSearchable.length} resource(s) ignore ?search= silently.`,
          { mode: 'resources', resources: SEARCH_RESOURCES, modes: SEARCH_MODES.map((m) => m.mode) },
        );
      }
      // mode === 'search'
      if (typeof args.query !== 'string' || args.query.length === 0) {
        return errorContent(
          configError(
            'hudu_search: mode="search" (the default) requires a non-empty query. It did NOT fall back to help. Call hudu_search({mode:"help"}) for how to use this tool, or hudu_search({mode:"resources"}) for what is searchable.',
          ),
        );
      }
      try {
        const { resources, ...rest } = args;
        const result = await ops.searchKnowledge(args.query, {
          ...rest,
          ...(resources === undefined ? {} : { scope: resources }),
          tier: args.tier ?? 'index', // the TOOL's default: a complete answer, not a body-blind one
        } as Parameters<Operations['searchKnowledge']>[1]);
        const incomplete = result.meta.complete ? '' : ` (partial: ${(result.meta.reasons ?? []).join(', ')})`;
        const bodyBlind = result.meta.degraded ? ` DEGRADED (${result.meta.degraded.kind}): ${result.meta.degraded.advice}` : '';
        return ok(
          `Found ${result.hits.length} ranked match(es)${incomplete}.${bodyBlind}`,
          { mode: 'search', query: args.query, hits: result.hits as unknown[], meta: { ...result.meta, mode: 'search' } },
        );
      } catch (err) {
        return errorContent(err);
      }
    },
  );

  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_resolve_any',
    {
      title: 'Resolve Any',
      description: TOOL_DESCRIPTIONS['hudu_resolve_any'],
      inputSchema: z.object({
        identifier: IDENTIFIER.describe('Id, exact name/slug, or an identifier object; resolved against every requested resource.'),
        opts: z.object({ resources: SEARCHABLE_RESOURCES.describe('Resources to try; default all eight, in fan-out order.'), limit: LIMIT }).optional(),
      }),
      outputSchema: HITS_OUTPUT,
      // Derived from the curated manifest annotations (readOnlyHint / destructiveHint /
      // idempotentHint / openWorldHint); the SDK's ToolAnnotations type has exactly those keys.
      annotations: { readOnlyHint: true, openWorldHint: true },
      // Not part of ToolAnnotations: the gateway-side flags the manifest also states in the
      // description. Keep them on the tool so a gateway can gate approval without reading prose.
      _meta: { backingOperation: 'operations.resolveAny', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      const { identifier, opts } = args;
      try {
        const resources = opts?.resources;
      const limit = opts?.limit ?? DEFAULT_LIMIT;
      const resolved = await ops.resolveAny(identifier, { ...(resources ? { resources } : {}), limit });
      return ok(
        resolved.truncated.length
          ? `Found ${resolved.hits.length} candidate(s); these resources hit their scan cap and are undecided: ${resolved.truncated.join(', ')}.`
          : `Found ${resolved.hits.length} candidate(s).`,
        { hits: resolved.hits, total: resolved.hits.length, truncated: resolved.truncated, scanned: resolved.scanned },
      );
      } catch (err) {
        return errorContent(err);
      }
    },
  );

  // ---------------------------------------------------------------------------------------
  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_get_api_info',
    {
      title: 'Get Api Info',
      description: TOOL_DESCRIPTIONS['hudu_get_api_info'],
      inputSchema: z.object({
        identifier: IDENTIFIER.optional().describe('Optional identifier; omit it for the tenant-wide api info.'),
        opts: z.object({ expand: EXPAND }).optional(),
      }),
      outputSchema: ONE_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'api_info.resolve', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      try {
        const limit = args.opts?.limit ?? DEFAULT_LIMIT;
        const result = await hudu.apiInfo.resolve(args.identifier, args.opts);
        const rows = Array.isArray(result) ? result : [];
        return oneResult('api info', record);
      } catch (err) {
        return errorContent(err);
      }
    },
  );
  server.registerTool(
    'hudu_get_company_context',
    {
      title: 'Get Company Context',
      description: TOOL_DESCRIPTIONS['hudu_get_company_context'],
      inputSchema: z.object({
        id: z.number().int().describe('Numeric company id.'),
        opts: z.object({ limit: LIMIT, expand: EXPAND }).optional(),
      }),
      outputSchema: CONTEXT_OUTPUT,
      // Derived from the curated manifest annotations (readOnlyHint / destructiveHint /
      // idempotentHint / openWorldHint); the SDK's ToolAnnotations type has exactly those keys.
      annotations: { readOnlyHint: true, openWorldHint: true },
      // Not part of ToolAnnotations: the gateway-side flags the manifest also states in the
      // description. Keep them on the tool so a gateway can gate approval without reading prose.
      _meta: { backingOperation: 'companies.getContext', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      const { id, opts } = args;
      try {
        const limit = opts?.limit ?? DEFAULT_LIMIT;
      const context = opts?.expand
        ? await hudu.companies.getContext(id, { limit, expand: true })
        : await hudu.companies.getContext(id, { limit });
      return ok(`Context for company ${id}: assets, articles, websites and passwords, each bounded to ${limit}.`, { context });
      } catch (err) {
        return errorContent(err);
      }
    },
  );

  // ---------------------------------------------------------------------------------------
  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_get_article_context',
    {
      title: 'Get Article Context',
      description: TOOL_DESCRIPTIONS['hudu_get_article_context'],
      inputSchema: z.object({
        id: z.number().int().describe('Numeric article id (hudu_get_article_context takes the id; use hudu_search_across_resources or hudu_invoke with articles.resolve to find it).'),
        opts: z.object({ expand: EXPAND }).optional(),
      }),
      outputSchema: CONTEXT_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'articles.getContext', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      try {
        const limit = args.opts?.limit ?? DEFAULT_LIMIT;
        const result = await hudu.articles.getContext(args.id, args.opts);
        const rows = Array.isArray(result) ? result : [];
        return ok('Article context returned.', { context: result });
      } catch (err) {
        return errorContent(err);
      }
    },
  );
  server.registerTool(
    'hudu_get_asset_context',
    {
      title: 'Get Asset Context',
      description: TOOL_DESCRIPTIONS['hudu_get_asset_context'],
      inputSchema: z.object({
        identifier: ASSET_IDENTIFIER.describe('Id, name, slug, primary serial or { id, companyId }.'),
        opts: z.object({ limit: LIMIT, expand: EXPAND }).optional(),
      }),
      outputSchema: CONTEXT_OUTPUT,
      // Derived from the curated manifest annotations (readOnlyHint / destructiveHint /
      // idempotentHint / openWorldHint); the SDK's ToolAnnotations type has exactly those keys.
      annotations: { readOnlyHint: true, openWorldHint: true },
      // Not part of ToolAnnotations: the gateway-side flags the manifest also states in the
      // description. Keep them on the tool so a gateway can gate approval without reading prose.
      _meta: { backingOperation: 'assets.getContext', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      const { identifier, opts } = args;
      try {
        const limit = opts?.limit ?? DEFAULT_LIMIT;
      const context = opts?.expand
        ? await hudu.assets.getContext(identifier, { limit, expand: true })
        : await hudu.assets.getContext(identifier, { limit });
      return ok(`Context for the asset, each sub-list bounded to ${limit}.`, { context });
      } catch (err) {
        return errorContent(err);
      }
    },
  );

  // ---------------------------------------------------------------------------------------
  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_get_asset_layout',
    {
      title: 'Get Asset Layout',
      description: TOOL_DESCRIPTIONS['hudu_get_asset_layout'],
      inputSchema: z.object({
        identifier: IDENTIFIER.describe('Id, exact name/slug, or an identifier object.'),
        opts: z.object({ expand: EXPAND }).optional(),
      }),
      outputSchema: ONE_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'asset_layouts.resolve', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      try {
        const limit = args.opts?.limit ?? DEFAULT_LIMIT;
        const result = await hudu.assetLayouts.resolve(args.identifier, args.opts);
        const rows = Array.isArray(result) ? result : [];
        return oneResult('asset layout', result);
      } catch (err) {
        return errorContent(err);
      }
    },
  );

  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_get_folder',
    {
      title: 'Get Folder',
      description: TOOL_DESCRIPTIONS['hudu_get_folder'],
      inputSchema: z.object({
        identifier: IDENTIFIER.describe('Id, exact name/slug, or an identifier object.'),
        opts: z.object({ expand: EXPAND }).optional(),
      }),
      outputSchema: ONE_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'folders.resolve', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      try {
        const limit = args.opts?.limit ?? DEFAULT_LIMIT;
        const result = await hudu.folders.resolve(args.identifier, args.opts);
        const rows = Array.isArray(result) ? result : [];
        return oneResult('folder', result);
      } catch (err) {
        return errorContent(err);
      }
    },
  );
  server.registerTool(
    'hudu_find_asset_passwords_by_slug',
    {
      title: 'Find Asset Passwords By Slug',
      description: TOOL_DESCRIPTIONS['hudu_find_asset_passwords_by_slug'],
      inputSchema: z.object({
        identifier: IDENTIFIER.describe('Id, exact name/slug, or an identifier object.'),
        opts: z.object({ expand: EXPAND }).optional(),
      }),
      outputSchema: ONE_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'asset_passwords.findBySlug', sensitive: true, requiresApproval: false },
    },
    async (args) => {
      try {
        return oneResult('asset password', await hudu.assetPasswords.findBySlug(args.identifier, args.opts));
      } catch (err) {
        return errorContent(err);
      }
    },
  );

  server.registerTool(
    'hudu_find_websites_by_slug',
    {
      title: 'Find Websites By Slug',
      description: TOOL_DESCRIPTIONS['hudu_find_websites_by_slug'],
      inputSchema: z.object({
        identifier: IDENTIFIER.describe('Id, exact name/slug, or an identifier object.'),
        opts: z.object({ expand: EXPAND }).optional(),
      }),
      outputSchema: ONE_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'websites.findBySlug', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      try {
        return oneResult('website', await hudu.websites.findBySlug(args.identifier, args.opts));
      } catch (err) {
        return errorContent(err);
      }
    },
  );

  server.registerTool(
    'hudu_get_password_folder',
    {
      title: 'Get Password Folder',
      description: TOOL_DESCRIPTIONS['hudu_get_password_folder'],
      inputSchema: z.object({
        identifier: IDENTIFIER.describe('Id, exact name/slug, or an identifier object.'),
        opts: z.object({ expand: EXPAND }).optional(),
      }),
      outputSchema: ONE_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'password_folders.resolve', sensitive: true, requiresApproval: false },
    },
    async (args) => {
      try {
        return oneResult('password folder', await hudu.passwordFolders.resolve(args.identifier, args.opts));
      } catch (err) {
        return errorContent(err);
      }
    },
  );

  server.registerTool(
    'hudu_get_group',
    {
      title: 'Get Group',
      description: TOOL_DESCRIPTIONS['hudu_get_group'],
      inputSchema: z.object({
        identifier: IDENTIFIER.describe('Id, exact name/slug, or an identifier object.'),
        opts: z.object({ expand: EXPAND }).optional(),
      }),
      outputSchema: ONE_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'groups.resolve', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      try {
        return oneResult('group', await hudu.groups.resolve(args.identifier, args.opts));
      } catch (err) {
        return errorContent(err);
      }
    },
  );
  return server;
});

process.on('uncaughtException', (err) => {
  console.error('uncaught exception:', err instanceof Error ? err.stack ?? err.message : err);
  void handle.close().finally(() => process.exit(1));
});

console.error('hudu MCP server running over stdio (MCP v2, protocol 2026-07-28)');
