/**
 * mcp-server.ts — reference Model Context Protocol (MCP) v2 server backed by node-hudu.
 *
 * Protocol 2026-07-28, official SDK v2 (`@modelcontextprotocol/server`), zod v4
 * (`import * as z from 'zod/v4'`), `structuredContent` paired with an `outputSchema` per tool.
 *
 * Ground rules this example follows (see MCP_TOOL_MANIFEST.md, curated by MCP_TOOL_OVERRIDES.json):
 * - Every READ tool calls the SDK's HELPER tier: `search`, `findBy*`, `resolve`, `getContext`, or
 *   the cross-resource `operations.searchAcrossResources` / `operations.resolveAny`. No tool is
 *   backed by `listAll`, `listPages`, or a streaming `list`.
 * - Results are BOUNDED: `limit` defaults to 25 and hard-caps at 100 on every read tool. The SDK
 *   validates the bound and throws `CONFIG_ERROR` above it — it never silently clamps.
 * - Every MUTATING tool exposes `dry_run`, which calls the SDK's `{ dryRun: true }` path and
 *   returns a `DryRunResult` (`simulated: true`, impact, diff) without issuing the write.
 * - Tool names, titles and descriptions are the curated ones from `MCP_TOOL_MANIFEST.md`;
 *   `npm run mcp:project -- --check-example` fails if this file drifts from that manifest.
 * - Errors surface `HuduError.code` (NOT_FOUND, RESOLUTION_AMBIGUOUS, POLICY_DENIED, …) so a
 *   model can self-correct instead of retrying blindly.
 *
 * PROGRESSIVE DISCLOSURE (`.run/design/search/progressive-disclosure.md`): this is a REFERENCE
 * CONSUMER, and the tool list it registers is the generated CORE profile — the curated manifest
 * projects 148 tools, of which a client must carry all 148 on every turn. The CORE set (rule in
 * `scripts/project-mcp-tools.mjs`, generated into `examples/tool-catalog.generated.ts`) is the
 * small always-present surface: R1 discover (`hudu_catalog` / `hudu_describe` / `hudu_invoke`),
 * R2 identify the tenant, R3 find a record the caller cannot name, R4 one read entry per group-A
 * workflow resource. Every OTHER operation stays REACHABLE through `hudu_invoke`, which validates
 * against the registry record before any request, forces a dry run on writes and refuses a
 * destructive operation without its confirmation flag. Nothing is removed from the surface: the
 * 56 operations curation dropped as duplicate outcomes and the 22 the projection never exposes are
 * catalogued as rows (the refused ones with `reachable: false` and the reason).
 *
 * Declared profile: `core`. `HUDU_MCP_PROFILE=extended|all` is the host knob documented in
 * MCP_TOOL_MANIFEST.md; this reference server demonstrates the `core` profile only.
 *
 * Requires:  npm install @modelcontextprotocol/server zod      (both are devDependencies here)
 * Run with:  HUDU_BASE_URL=https://hudu.example.com HUDU_API_KEY=xxx npx tsx examples/mcp-server.ts
 *
 * Note: MCP SDK v2 requires Node >= 20.
 */
import { McpServer } from '@modelcontextprotocol/server';
import { serveStdio } from '@modelcontextprotocol/server/stdio';
import * as z from 'zod/v4';
import { HuduClient } from 'node-hudu';
import { Operations } from 'node-hudu/operations';
import { getCapability } from 'node-hudu/capabilities';
// Generated by `node scripts/build-tool-catalog.mjs` from the capability registry. DO NOT HAND-EDIT.
// It carries the CORE profile, the three META tool specs, the catalog rows and the runtime helpers
// (catalog paging, describe, input validation, the write governor). It imports nothing: the SDK
// stays MCP-independent and this server passes the registry record in.
import {
  META_TOOLS,
  catalogPage,
  configError,
  describeOperation,
  governInvoke,
  inputFields,
  requireCatalogRow,
  validateInvokeInput,
} from './tool-catalog.generated.js';

const baseUrl = process.env.HUDU_BASE_URL;
const apiKey = process.env.HUDU_API_KEY;

if (!baseUrl || !apiKey) {
  throw new Error('HUDU_BASE_URL and HUDU_API_KEY must be set');
}

/**
 * The profile this example registers, read by `npm run mcp:project -- --check-example` (which then
 * requires exactly the generated CORE set + the three META tools, with their descriptions verbatim).
 * `core` is the token-budget profile; see the header. The extended profile is the curated manifest
 * (147 tools) and is not demonstrated here on purpose — a reference server that shipped 147 tools
 * would be the problem this design removes.
 */
const MCP_PROFILE = 'core';

/** Helper `limit` bounds (manifest: "default 25 results, hard maximum 100"). */
const DEFAULT_LIMIT = 25;
const MAX_LIMIT = 100;

/** The eight resources the cross-resource helpers can reach, in their documented fan-out order. */
const SEARCHABLE_RESOURCES = z.array(
  z.enum([
    'companies',
    'articles',
    'assets',
    'websites',
    'asset_passwords',
    'password_folders',
    'groups',
    'users',
  ]),
);

/** Every read tool's bound, stated identically everywhere. */
const LIMIT = z
  .number()
  .int()
  .min(1)
  .max(MAX_LIMIT)
  .default(DEFAULT_LIMIT)
  .describe('Maximum rows returned (1-100, default 25). A larger value throws CONFIG_ERROR - the SDK never silently clamps.');

const EXPAND = z
  .boolean()
  .default(false)
  .describe('Return the full typed records instead of the compact summaries (default false).');

const DRY_RUN = z
  .boolean()
  .default(false)
  .describe('Validate without issuing the write: returns a DryRunResult with simulated: true, the impact and the diff. Dry-run every destructive or approval-gated call first.');

/** Accepts a bare id/name/slug or the identifier object the resource documents. */
const IDENTIFIER = z.union([
  z.number().int(),
  z.string().min(1),
  z.object({
    id: z.number().int().optional().describe('Numeric id - the direct fetch.'),
    name: z.string().optional().describe('Exact name.'),
    slug: z.string().optional().describe('Exact slug.'),
    external_id: z.string().optional().describe('Vendor-side external id.'),
    domain: z.string().optional().describe('Domain, for resources that have one.'),
  }),
]);

/** `companies.resolve` also accepts a website. */
const COMPANY_IDENTIFIER = z.union([
  z.number().int(),
  z.string().min(1),
  z.object({
    id: z.number().int().optional(),
    name: z.string().optional(),
    slug: z.string().optional(),
    website: z.string().optional(),
    domain: z.string().optional(),
  }),
]);

/** `assets.resolve` / `assets.getContext` also accept a primary serial and a company scope. */
const ASSET_IDENTIFIER = z.union([
  z.number().int(),
  z.string().min(1),
  z.object({
    id: z.number().int().optional(),
    companyId: z.number().int().optional(),
    name: z.string().optional(),
    slug: z.string().optional(),
    primary_serial: z.string().optional(),
  }),
]);

/**
 * Row shape of a compact summary (`CompanySummary`, `ArticleSummary`, …).
 *
 * Stays loose on purpose: the exact kept/dropped field list is published per resource in
 * MCP_TOOL_MANIFEST.md (`outputSchema.drops`). Restating it here would add ~15 fields of JSON
 * schema per resource for no extra information the model does not already have.
 */
const ROWS = z.array(z.unknown());

/** One row of a bounded list result. `hasMore` is a hint: the SDK returned exactly `limit` rows. */
const LIST_OUTPUT = z.object({
  items: ROWS,
  total: z.number(),
  limit: z.number(),
  hasMore: z.boolean(),
});

/** One resolved record: `found: false` is a complete answer, not an error. */
const ONE_OUTPUT = z.object({ found: z.boolean(), record: z.unknown() });

/** A cross-resource result; `truncated` names resources whose scan hit its cap (undecided). */
const HITS_OUTPUT = z.object({
  hits: z.array(
    z.object({ resource: z.string(), id: z.number(), label: z.string(), item: z.unknown() }),
  ),
  total: z.number(),
  truncated: z.array(z.string()),
  scanned: z.number(),
});

/** A knowledge search result: ranked hits (each carrying its own fetch call) plus the response metadata. */
const KNOWLEDGE_OUTPUT = z.object({ hits: z.array(z.unknown()), meta: z.unknown() });

/** A bundled context read (`getContext`, `getWithTasks`). */
const CONTEXT_OUTPUT = z.object({ context: z.unknown() });

/** A catalog page (`hudu_catalog`): counts plus the rows the filters matched. */
const CATALOG_OUTPUT = z.object({
  total_operations: z.number(),
  reachable_operations: z.number(),
  unexposed_operations: z.number(),
  unreachable_operations: z.number(),
  matched: z.number(),
  offset: z.number(),
  limit: z.number(),
  has_more: z.boolean(),
  rows: z.array(z.unknown()),
});

/** An `hudu_invoke` result: `simulated: true` means the dry-run path ran and nothing was written. */
const INVOKE_OUTPUT = z.object({ simulated: z.boolean(), operation: z.string(), result: z.unknown() });

/** A write result: `simulated: true` means the dry-run path ran and nothing was written. */
const WRITE_OUTPUT = z.object({ simulated: z.boolean(), result: z.unknown() });

type ToolReturn =
  | { content: Array<{ type: 'text'; text: string }>; structuredContent: Record<string, unknown> }
  | { content: Array<{ type: 'text'; text: string }>; isError: true };

/** A successful structured result. `outputSchema` describes `structuredContent`. */
function ok(text: string, structuredContent: Record<string, unknown>): ToolReturn {
  return { content: [{ type: 'text', text }], structuredContent };
}

/** Bounded list result: the count is the number of rows actually returned. */
function listResult(what: string, items: unknown[], limit: number): ToolReturn {
  return ok(`${items.length} ${what} record(s) returned (bound ${limit}).`, {
    items,
    total: items.length,
    limit,
    hasMore: items.length >= limit,
  });
}

/** One-record result. A `null` from a helper is a complete, bounded "no match" answer. */
function oneResult(what: string, record: unknown): ToolReturn {
  return ok(record === null ? `No ${what} matched.` : `${what} resolved.`, {
    found: record !== null,
    record,
  });
}

/** Surface `HuduError.code` (and HTTP status) so the model can correct itself. */
function errorContent(err: unknown): ToolReturn {
  const code = (err as { code?: string })?.code;
  const status = (err as { status?: number })?.status;
  const message = err instanceof Error ? err.message : String(err);
  return {
    content: [{ type: 'text', text: JSON.stringify({ error: true, code, status, message }) }],
    isError: true,
  };
}

const handle = serveStdio(() => {
  const hudu = new HuduClient({ baseUrl, apiKey });
  /** Cross-resource reads (`searchAcrossResources`, `resolveAny`); same client, no extra config. */
  const ops = new Operations(hudu);

  /**
   * Dispatch for `hudu_invoke`: resolve the SDK's OWN method for a canonical operation key
   * (`companies.update` -> `hudu.companies.update`). The registry resource key is camel-cased to the
   * client property the SDK exposes (`asset_layouts` -> `assetLayouts`), and the call is made
   * POSITIONALLY in the registry's declared field order (`id`, `data`, `opts`) — the order the
   * generator derived from the method's own parameters. So there is no per-operation glue and no
   * second write path here: the SDK method runs, with its guards, retries and error vocabulary.
   */
  const resolveMethod = (op: string): ((...args: unknown[]) => Promise<unknown>) | null => {
    const [resourceKey, ...rest] = op.split('.');
    const property = (resourceKey ?? '').replace(/_(\w)/g, (_m: string, c: string) => c.toUpperCase());
    const owner = (hudu as unknown as Record<string, unknown>)[property];
    if (typeof owner !== 'object' || owner === null) return null;
    const fn = (owner as Record<string, unknown>)[rest.join('.')];
    if (typeof fn !== 'function') return null;
    return (fn as (...args: unknown[]) => Promise<unknown>).bind(owner);
  };

  const server = new McpServer({
    name: 'hudu-mcp',
    version: '0.3.0',
    title: 'Hudu MCP Server',
    websiteUrl: 'https://github.com/msoukhomlinov/node-hudu',
  });


  // =========================================================================================
  // META TOOLS (R1) - the generated catalog, the per-operation describe, and the escape hatch.
  // Always present, and the reason the 147-tool curated surface is reachable without being paid
  // for on every turn. `hudu_invoke` is safe through the SDK's own guards, not through this
  // shorter tool list: the registry record is validated before any request, writes are
  // dry-run-first, and a destructive operation needs `confirm` to equal its operation key.
  // =========================================================================================
  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_catalog',
    {
      title: 'Discover Operations (Catalog)',
      description: 'List the operations the Hudu SDK implements, with the tool that exposes each one (when it has one), its effect, whether it needs a dry run or a confirmation flag, and the arguments it requires. The tool list on this server is a SUBSET: this is a curated core profile, and the catalog is how you discover a capability that has no tool of its own — find the row, call hudu_describe for the exact schema, then hudu_invoke. Rows with no "tool" are reachable only through hudu_invoke. Rows with "reachable": false are deliberately not callable here and state why (an unbounded read, or a binary/download surface). Bounded: limit defaults to 40 and is hard-capped at 100, offset pages through the rest; the whole catalog is ~10k tokens, so ask for a filter or a page rather than dumping it.',
      inputSchema: z.object({
        limit: z.number().int().min(1).max(100).default(40).describe('Rows per page (1-100, default 40); the whole catalog is ~10k tokens, so page it.'),
        offset: z.number().int().min(0).default(0).describe('Row offset, for paging.'),
        effect: z.enum(['read', 'write', 'destructive']).optional().describe('Only rows with this effect.'),
        resource: z.string().optional().describe('Only rows of this registry resource (e.g. "assets").'),
        unexposed_only: z.boolean().optional().describe('Only rows with NO tool of their own — the capabilities reachable only through hudu_invoke.'),
      }),
      outputSchema: CATALOG_OUTPUT,
      annotations: { readOnlyHint: false, openWorldHint: true },
      _meta: { backingOperation: '— (serves the whole registry)', dryRunAffordance: "dry_run", registryWide: true },
    },
    async (args) => {
      try {
        const page = catalogPage(args);
        const text = `${page.rows.length} of ${page.matched} matching operation(s) shown (offset ${page.offset}, bound ${page.limit}). The registry holds ${page.total_operations} operations; ${page.unexposed_operations} of them have NO tool of their own and are reached with hudu_invoke; ${page.unreachable_operations} are deliberately not callable here (see the row's reason and bounded alternative).`;
        return ok(text, { ...page });
      } catch (err) {
        return errorContent(err);
      }
    },
  );
  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_describe',
    {
      title: 'Describe One Operation',
      description: 'Return the full input schema, effect, flags, dry-run support, error vocabulary, related operations and preferredWhen guidance for ONE operation, so a capability can be called correctly without carrying every schema in context. Use it after hudu_catalog named the operation and before hudu_invoke. Takes the canonical operation key exactly as the catalog prints it (for example "companies.update") — never a tool name, and there is no fuzzy matching: an unknown key is a CONFIG_ERROR naming the nearest catalog keys.',
      inputSchema: z.object({
        operation: z.string().min(1).describe('Canonical operation key exactly as hudu_catalog prints it, e.g. "companies.update". Never a tool name; there is no fuzzy match.'),
      }),
      outputSchema: z.object({ op: z.string() }).passthrough(),
      annotations: { readOnlyHint: false, openWorldHint: true },
      _meta: { backingOperation: '— (serves the whole registry)', dryRunAffordance: "dry_run", registryWide: true },
    },
    async (args) => {
      try {
        const { operation } = args;
        const record = getCapability(operation);
        // Unknown key: requireCatalogRow throws CONFIG_ERROR naming the nearest catalog keys
        // (exact-key lookup only — there is no fuzzy execution anywhere in this server).
        if (record === undefined) requireCatalogRow(operation);
        const described = describeOperation(record);
        return ok(`${operation}: ${described.effect}${described.reachable ? '' : ' — NOT callable here: ' + described.why_not}`, { ...described });
      } catch (err) {
        return errorContent(err);
      }
    },
  );
  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_invoke',
    {
      title: 'Invoke Any Operation (Escape Hatch)',
      description: 'Execute an operation by its canonical registry key, including the ones with no tool of their own. The input is validated against the registry record BEFORE any HTTP request: unknown fields, missing required fields, wrong types and out-of-enum values are refused with CONFIG_ERROR and the field path, and no request is issued. Reads run directly. Writes are dry-run-first: call with dry_run: true to get the SDK\'s dry-run result (simulated: true, the impact and the diff) with no request issued — a write without dry_run: true is refused, and a destructive or approval-gated operation also requires confirm to equal the operation key exactly. Operations the projection never exposes (unbounded listAll/listPages reads, binary/download resources) are refused with a reason and the bounded alternative where one exists. This is the escape hatch for the long tail, not the common path: prefer a typed tool when one fits, and read the schema with hudu_describe first when the arguments are not obvious.',
      inputSchema: z.object({
        operation: z.string().min(1).describe('Canonical operation key (see hudu_catalog). Exact registry key, never a tool name.'),
        input: z.record(z.string(), z.unknown()).optional().describe('The operation arguments as one object; validated against the registry record before any request.'),
        dry_run: z.boolean().default(false).describe('Required for any write: runs the SDK dry-run path (simulated: true, impact and diff) with no request issued.'),
        confirm: z.string().optional().describe('For a destructive or approval-gated operation: must equal the operation key exactly, or the call is refused.'),
      }),
      outputSchema: INVOKE_OUTPUT,
      annotations: { readOnlyHint: false, openWorldHint: true },
      _meta: { backingOperation: '— (whole registry, by canonical key)', dryRunAffordance: "dry_run", registryWide: true },
    },
    async (args) => {
      const { operation, input, dry_run, confirm } = args;
      try {
        const record = getCapability(operation);
        if (record === undefined) requireCatalogRow(operation);
        // 1. Registry validation BEFORE any request: unknown fields, missing required fields,
        //    wrong types and out-of-enum values are refused with the field path.
        const validated = validateInvokeInput(record, input);
        if (!validated.ok) return errorContent(configError(validated.message));
        // 2. Write governor: dry-run-first on writes, confirm on destructive/approval-gated ones,
        //    and a refusal for the operations the projection deliberately never exposes.
        const governed = governInvoke(record, { dry_run, confirm });
        if (!governed.ok) return errorContent(configError(governed.message));
        // 3. Dispatch through the SDK's OWN method for this operation, positionally in the
        //    registry's declared field order — the same call path, guards, retries and error
        //    vocabulary the typed tools use. No second implementation of any write.
        const method = resolveMethod(record.name);
        if (method === null) {
          return errorContent(configError(`hudu_invoke: ${record.name} has no dispatchable SDK method (reference-server defect, not a call error).`));
        }
        const fields = inputFields(record.inputSchema);
        const given = (input ?? {}) as Record<string, unknown>;
        const positional = fields.map((f) => given[f.name]);
        if (governed.dry_run) {
          const optsIndex = fields.findIndex((f) => f.name === 'opts');
          const dryRunOpts = { dryRun: true };
          if (optsIndex === -1) positional.push(dryRunOpts);
          else positional[optsIndex] = { ...((positional[optsIndex] as Record<string, unknown> | undefined) ?? {}), ...dryRunOpts };
        }
        while (positional.length > 0 && positional[positional.length - 1] === undefined) positional.pop();
        const result = await method(...positional);
        return ok(
          governed.dry_run ? `Dry run: nothing was written (${operation}).` : `${operation} completed.`,
          { simulated: governed.dry_run, operation, result: result ?? null },
        );
      } catch (err) {
        return errorContent(err);
      }
    },
  );

  // =========================================================================================
  // CORE READ TOOLS (R2 / R3 / R4) - helper tier only (search / resolve / getContext).
  // =========================================================================================
  server.registerTool(
    'hudu_search_across_resources',
    {
      title: 'Search Across Resources',
      description: 'Search several Hudu resources for one query in a single bounded call. Preferred over calling several resources\' search methods yourself whenever the caller does not know which resource holds the record. Returns one SearchHit row per match as { resource, id, label, item }, in resource order (expand: true returns the full typed records). Bounded: limit defaults to 25 and is hard-capped at 100; a larger value throws CONFIG_ERROR and is never silently clamped. Do not use it when the resource type is known: that resource\'s own hudu_search_<resource> issues one request instead of eight.',
      inputSchema: z.object({
        query: z.string().min(1).describe('Text to search every requested resource for.'),
        opts: z.object({ resources: SEARCHABLE_RESOURCES.describe('Resources to search; default all eight, in fan-out order.'), limit: LIMIT, expand: EXPAND }).optional(),
      }),
      outputSchema: HITS_OUTPUT,
      // Derived from the curated manifest annotations (readOnlyHint / destructiveHint /
      // idempotentHint / openWorldHint); the SDK's ToolAnnotations type has exactly those keys.
      annotations: { readOnlyHint: true, openWorldHint: true },
      // Not part of ToolAnnotations: the gateway-side flags the manifest also states in the
      // description. Keep them on the tool so a gateway can gate approval without reading prose.
      _meta: { backingOperation: 'operations.searchAcrossResources', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      const { query, opts } = args;
      try {
        const resources = opts?.resources;
      const limit = opts?.limit ?? DEFAULT_LIMIT;
      const hits = opts?.expand
        ? await ops.searchAcrossResources(query, { ...(resources ? { resources } : {}), limit, expand: true })
        : await ops.searchAcrossResources(query, { ...(resources ? { resources } : {}), limit });
      return ok(`Found ${hits.length} matching record(s) across resources.`, { hits, total: hits.length, truncated: [], scanned: hits.length });
      } catch (err) {
        return errorContent(err);
      }
    },
  );

  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_search_knowledge',
    {
      title: 'Search Knowledge',
      description: 'Search the knowledge base by content, articles first and assets second, with typo tolerance, ranked hits and verbatim snippets. Preferred over articles.search and assets.search for a phrase inside an article body, a mistyped title, a serial or a custom-field value: Hudu search matches titles only and needs an exact substring. Each hit carries its own fetch call for the full record. Bounded: scope defaults to articles and assets, limit defaults to 8 with a hard maximum of 25, and every bound that bit is named. A cold index is answered from Hudu search alone and says so. Do not use it for an exact id, a slug or a domain.',
      inputSchema: z.object({
        query: z.string().min(1).describe('Text to search the knowledge base for; word order and typos are tolerated.'),
        opts: z
          .object({
            scope: z.array(z.enum(['articles', 'assets', 'companies', 'users', 'groups', 'websites', 'asset_passwords', 'password_folders'])).optional(),
            limit: z.number().int().min(1).max(25).optional(),
            snippetChars: z.number().int().min(1).max(400).optional(),
            company_id: z.number().int().optional(),
            updated_since: z.string().optional(),
            min_score: z.number().optional(),
            exact_only: z.boolean().optional(),
            tier: z.enum(['auto', 'vendor', 'index']).optional(),
            refresh: z.boolean().optional(),
          })
          .optional(),
      }),
      outputSchema: KNOWLEDGE_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'operations.searchKnowledge', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      const { query, opts } = args;
      try {
        const result = await ops.searchKnowledge(query, opts ?? {});
        return ok(
          `Found ${result.hits.length} matching record(s)${result.meta.complete ? '' : ' (bounded: ' + result.meta.reasons.join(', ') + ')'}.`,
          result as unknown as Record<string, unknown>,
        );
      } catch (err) {
        return errorContent(err);
      }
    },
  );

  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_resolve_any',
    {
      title: 'Resolve Any',
      description: 'Resolve an identifier against several resources and return the candidates that match. Preferred when the caller has an identifier but not the resource type; use the resource\'s own resolve when the type is known. Returns ResolutionCandidateHit rows for each resource that matched, with scanned/truncated counts; it does not throw RESOLUTION_AMBIGUOUS across resources. Bounded: limit defaults to 25 and is hard-capped at 100; a larger value throws CONFIG_ERROR and is never silently clamped. Do not use it when the resource type is known: call that resource\'s hudu_get_<singular>.',
      inputSchema: z.object({
        identifier: IDENTIFIER.describe('Id, exact name/slug, or an identifier object; resolved against every requested resource.'),
        opts: z.object({ resources: SEARCHABLE_RESOURCES.describe('Resources to try; default all eight, in fan-out order.'), limit: LIMIT }).optional(),
      }),
      outputSchema: HITS_OUTPUT,
      // Derived from the curated manifest annotations (readOnlyHint / destructiveHint /
      // idempotentHint / openWorldHint); the SDK's ToolAnnotations type has exactly those keys.
      annotations: { readOnlyHint: true, openWorldHint: true },
      // Not part of ToolAnnotations: the gateway-side flags the manifest also states in the
      // description. Keep them on the tool so a gateway can gate approval without reading prose.
      _meta: { backingOperation: 'operations.resolveAny', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      const { identifier, opts } = args;
      try {
        const resources = opts?.resources;
      const limit = opts?.limit ?? DEFAULT_LIMIT;
      const resolved = await ops.resolveAny(identifier, { ...(resources ? { resources } : {}), limit });
      return ok(
        resolved.truncated.length
          ? `Found ${resolved.hits.length} candidate(s); these resources hit their scan cap and are undecided: ${resolved.truncated.join(', ')}.`
          : `Found ${resolved.hits.length} candidate(s).`,
        { hits: resolved.hits, total: resolved.hits.length, truncated: resolved.truncated, scanned: resolved.scanned },
      );
      } catch (err) {
        return errorContent(err);
      }
    },
  );

  // ---------------------------------------------------------------------------------------
  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_get_api_info',
    {
      title: 'Get Api Info',
      description: 'Return the API information document. Prefer api_info.get; this exists so every resource satisfies the same floor. Bounded: limit defaults to 25 with a hard maximum of 100, and the client scan stops at 500 records / 4 pages (it throws RESOLUTION_TRUNCATED rather than returning a partial answer). Do not use it for free-text discovery across many records: call hudu_search_api_info (or hudu_search_across_resources when the resource type is unknown).',
      inputSchema: z.object({
        identifier: IDENTIFIER.optional().describe('Optional identifier; omit it for the tenant-wide api info.'),
        opts: z.object({ expand: EXPAND }).optional(),
      }),
      outputSchema: ONE_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'api_info.resolve', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      try {
        const limit = args.opts?.limit ?? DEFAULT_LIMIT;
        const result = await hudu.apiInfo.resolve(args.identifier, args.opts);
        const rows = Array.isArray(result) ? result : [];
        return oneResult('api info', record);
      } catch (err) {
        return errorContent(err);
      }
    },
  );
  server.registerTool(
    'hudu_get_company_context',
    {
      title: 'Get Company Context',
      description: 'Fetch a company together with the bounded context an agent needs about it. Preferred over four separate list calls when an agent starts work on a company. Returns CompanyContext. Bounded: every sub-list is fetched with limit, default 25, hard maximum 100 — no sub-fetch walks the account. Do not use it to page a resource: call hudu_search_companies. It issues several bounded reads per call.',
      inputSchema: z.object({
        id: z.number().int().describe('Numeric company id.'),
        opts: z.object({ limit: LIMIT, expand: EXPAND }).optional(),
      }),
      outputSchema: CONTEXT_OUTPUT,
      // Derived from the curated manifest annotations (readOnlyHint / destructiveHint /
      // idempotentHint / openWorldHint); the SDK's ToolAnnotations type has exactly those keys.
      annotations: { readOnlyHint: true, openWorldHint: true },
      // Not part of ToolAnnotations: the gateway-side flags the manifest also states in the
      // description. Keep them on the tool so a gateway can gate approval without reading prose.
      _meta: { backingOperation: 'companies.getContext', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      const { id, opts } = args;
      try {
        const limit = opts?.limit ?? DEFAULT_LIMIT;
      const context = opts?.expand
        ? await hudu.companies.getContext(id, { limit, expand: true })
        : await hudu.companies.getContext(id, { limit });
      return ok(`Context for company ${id}: assets, articles, websites and passwords, each bounded to ${limit}.`, { context });
      } catch (err) {
        return errorContent(err);
      }
    },
  );

  // ---------------------------------------------------------------------------------------
  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_get_article_context',
    {
      title: 'Get Article Context',
      description: 'Fetch an article with its company and folder context. Preferred over three separate calls when an agent starts from an article. Returns ArticleContext. Bounded: every sub-list is fetched with limit, default 25, hard maximum 100 — no sub-fetch walks the account. Do not use it to page a resource: call hudu_search_articles. It issues several bounded reads per call.',
      inputSchema: z.object({
        id: z.number().int().describe('Numeric article id (hudu_get_article_context takes the id; use hudu_search_across_resources or hudu_invoke with articles.resolve to find it).'),
        opts: z.object({ expand: EXPAND }).optional(),
      }),
      outputSchema: CONTEXT_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'articles.getContext', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      try {
        const limit = args.opts?.limit ?? DEFAULT_LIMIT;
        const result = await hudu.articles.getContext(args.id, args.opts);
        const rows = Array.isArray(result) ? result : [];
        return ok('Article context returned.', { context: result });
      } catch (err) {
        return errorContent(err);
      }
    },
  );
  server.registerTool(
    'hudu_get_asset_context',
    {
      title: 'Get Asset Context',
      description: 'Fetch an asset with the context an agent needs about it. Preferred over four separate calls when an agent starts from an asset. Returns AssetContext. Bounded: every sub-list is fetched with limit, default 25, hard maximum 100 — no sub-fetch walks the account. Do not use it to page a resource: call hudu_search_assets. It issues several bounded reads per call.',
      inputSchema: z.object({
        identifier: ASSET_IDENTIFIER.describe('Id, name, slug, primary serial or { id, companyId }.'),
        opts: z.object({ limit: LIMIT, expand: EXPAND }).optional(),
      }),
      outputSchema: CONTEXT_OUTPUT,
      // Derived from the curated manifest annotations (readOnlyHint / destructiveHint /
      // idempotentHint / openWorldHint); the SDK's ToolAnnotations type has exactly those keys.
      annotations: { readOnlyHint: true, openWorldHint: true },
      // Not part of ToolAnnotations: the gateway-side flags the manifest also states in the
      // description. Keep them on the tool so a gateway can gate approval without reading prose.
      _meta: { backingOperation: 'assets.getContext', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      const { identifier, opts } = args;
      try {
        const limit = opts?.limit ?? DEFAULT_LIMIT;
      const context = opts?.expand
        ? await hudu.assets.getContext(identifier, { limit, expand: true })
        : await hudu.assets.getContext(identifier, { limit });
      return ok(`Context for the asset, each sub-list bounded to ${limit}.`, { context });
      } catch (err) {
        return errorContent(err);
      }
    },
  );

  // ---------------------------------------------------------------------------------------
  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_get_asset_layout',
    {
      title: 'Get Asset Layout',
      description: 'Resolve an asset layout from an id, name or slug. Use when the identifier is a layout name or slug; asset_layouts.get is cheaper for a known id. Returns one record: a compact AssetLayoutSummary (icon_color, sidebar_folder_id, include_passwords, … dropped); expand: true returns the full AssetLayout. Bounded: limit defaults to 25 with a hard maximum of 100, and the client scan stops at 500 records / 4 pages (it throws RESOLUTION_TRUNCATED rather than returning a partial answer). Do not use it for free-text discovery across many records: call hudu_search_asset_layouts (or hudu_search_across_resources when the resource type is unknown).',
      inputSchema: z.object({
        identifier: IDENTIFIER.describe('Id, exact name/slug, or an identifier object.'),
        opts: z.object({ expand: EXPAND }).optional(),
      }),
      outputSchema: ONE_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'asset_layouts.resolve', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      try {
        const limit = args.opts?.limit ?? DEFAULT_LIMIT;
        const result = await hudu.assetLayouts.resolve(args.identifier, args.opts);
        const rows = Array.isArray(result) ? result : [];
        return oneResult('asset layout', result);
      } catch (err) {
        return errorContent(err);
      }
    },
  );
  server.registerTool(
    'hudu_search_asset_passwords',
    {
      title: 'Search Asset Passwords',
      description: 'Search password records by a free-text query. Preferred over asset_passwords.list for any text search. Returns rows: a compact AssetPasswordSummary (passwordable_id, passwordable_type, description, … dropped); expand: true returns the full AssetPassword. Bounded: limit defaults to 25 and is hard-capped at 100; a larger value throws CONFIG_ERROR and is never silently clamped. Do not use it when you already have an id, slug or domain: call hudu_get_asset_password instead. Sensitive: it returns credential-shaped fields; the SDK redacts them from logs and audit payloads by default.',
      inputSchema: z.object({
        query: z.string().min(1).describe('Partial password entry name or username.'),
        opts: z.object({ limit: LIMIT, expand: EXPAND.describe('Return the full records, including secrets. Off by default: the summaries omit credential fields.') }).optional(),
      }),
      outputSchema: LIST_OUTPUT,
      // Derived from the curated manifest annotations (readOnlyHint / destructiveHint /
      // idempotentHint / openWorldHint); the SDK's ToolAnnotations type has exactly those keys.
      annotations: { readOnlyHint: true, openWorldHint: true },
      // Not part of ToolAnnotations: the gateway-side flags the manifest also states in the
      // description. Keep them on the tool so a gateway can gate approval without reading prose.
      _meta: { backingOperation: 'asset_passwords.search', sensitive: true, requiresApproval: false },
    },
    async (args) => {
      const { query, opts } = args;
      try {
        const limit = opts?.limit ?? DEFAULT_LIMIT;
      const items = opts?.expand
        ? await hudu.assetPasswords.search(query, { limit, expand: true })
        : await hudu.assetPasswords.search(query, { limit });
      return listResult('asset_passwords', items, limit);
      } catch (err) {
        return errorContent(err);
      }
    },
  );

  // ---------------------------------------------------------------------------------------
  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_search_websites',
    {
      title: 'Search Websites',
      description: 'Search monitored websites by a free-text query. Preferred over websites.list for any text search. Returns rows: a compact WebsiteSummary (code, message, keyword, … dropped); expand: true returns the full Website. Bounded: limit defaults to 25 and is hard-capped at 100; a larger value throws CONFIG_ERROR and is never silently clamped. Do not use it when you already have an id, slug or domain: call hudu_get_website instead.',
      inputSchema: z.object({
        query: z.string().min(1).describe('Text to search websites for.'),
        opts: z.object({ limit: LIMIT, expand: EXPAND }).optional(),
      }),
      outputSchema: LIST_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'websites.search', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      try {
        const limit = args.opts?.limit ?? DEFAULT_LIMIT;
        const result = await hudu.websites.search(args.query, args.opts);
        const rows = Array.isArray(result) ? result : [];
        return listResult('website', rows, limit);
      } catch (err) {
        return errorContent(err);
      }
    },
  );
  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_get_folder',
    {
      title: 'Get Folder',
      description: 'Resolve a folder from an id or name, optionally scoped to a company. Use when the identifier is a folder name; folders.get is cheaper for a known id. Returns one record: a compact FolderSummary (description, created_at, … dropped); expand: true returns the full Folder. Bounded: limit defaults to 25 with a hard maximum of 100, and the client scan stops at 500 records / 4 pages (it throws RESOLUTION_TRUNCATED rather than returning a partial answer). Do not use it for free-text discovery across many records: call hudu_search_folders (or hudu_search_across_resources when the resource type is unknown).',
      inputSchema: z.object({
        identifier: IDENTIFIER.describe('Id, exact name/slug, or an identifier object.'),
        opts: z.object({ expand: EXPAND }).optional(),
      }),
      outputSchema: ONE_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'folders.resolve', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      try {
        const limit = args.opts?.limit ?? DEFAULT_LIMIT;
        const result = await hudu.folders.resolve(args.identifier, args.opts);
        const rows = Array.isArray(result) ? result : [];
        return oneResult('folder', result);
      } catch (err) {
        return errorContent(err);
      }
    },
  );
  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_search_password_folders',
    {
      title: 'Search Password Folders',
      description: 'Search password folders by a free-text query. Preferred over password_folders.list for any text search. Returns rows: a compact PasswordFolderSummary (description, allowed_groups, created_at, … dropped); expand: true returns the full PasswordFolder. Bounded: limit defaults to 25 and is hard-capped at 100; a larger value throws CONFIG_ERROR and is never silently clamped. Do not use it when you already have an id, slug or domain: call hudu_get_password_folder instead. Sensitive: it returns credential-shaped fields; the SDK redacts them from logs and audit payloads by default.',
      inputSchema: z.object({
        query: z.string().min(1).describe('Text to search password folders for.'),
        opts: z.object({ limit: LIMIT, expand: EXPAND }).optional(),
      }),
      outputSchema: LIST_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'password_folders.search', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      try {
        const limit = args.opts?.limit ?? DEFAULT_LIMIT;
        const result = await hudu.passwordFolders.search(args.query, args.opts);
        const rows = Array.isArray(result) ? result : [];
        return listResult('password folder', rows, limit);
      } catch (err) {
        return errorContent(err);
      }
    },
  );
  // ---------------------------------------------------------------------------------------
  server.registerTool(
    'hudu_search_groups',
    {
      title: 'Search Groups',
      description: 'Search groups by name. Preferred over groups.list for any group-name search. Returns rows: a compact GroupSummary (url, created_at, members, … dropped); expand: true returns the full Group. Bounded: limit defaults to 25 and is hard-capped at 100; a larger value throws CONFIG_ERROR and is never silently clamped. Do not use it when you already have an id, slug or domain: call hudu_get_group instead.',
      inputSchema: z.object({
        query: z.string().min(1).describe('Text to search groups for.'),
        opts: z.object({ limit: LIMIT, expand: EXPAND }).optional(),
      }),
      outputSchema: LIST_OUTPUT,
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { backingOperation: 'groups.search', sensitive: false, requiresApproval: false },
    },
    async (args) => {
      try {
        const limit = args.opts?.limit ?? DEFAULT_LIMIT;
        const result = await hudu.groups.search(args.query, args.opts);
        const rows = Array.isArray(result) ? result : [];
        return listResult('group', rows, limit);
      } catch (err) {
        return errorContent(err);
      }
    },
  );
  return server;
});

process.on('uncaughtException', (err) => {
  console.error('uncaught exception:', err instanceof Error ? err.stack ?? err.message : err);
  void handle.close().finally(() => process.exit(1));
});

console.error('hudu MCP server running over stdio (MCP v2, protocol 2026-07-28)');
